-- Monthly email performance reports
-- Generated by the /api/cron/monthly-email-report cron on the 1st of each month.
-- Stores the full HTML report + structured metrics for dashboard use.

create table if not exists monthly_email_reports (
  id                  uuid primary key default gen_random_uuid(),
  report_month        text not null unique,      -- "2026-09"
  report_label        text not null,             -- "September 2026"
  generated_at        timestamptz not null default now(),

  -- Campaign metrics
  campaigns_sent      integer     default 0,
  total_delivered     integer     default 0,
  total_revenue       numeric(10,2) default 0,
  campaign_revenue    numeric(10,2) default 0,
  flow_revenue        numeric(10,2) default 0,
  avg_open_rate       numeric(6,5)  default 0,
  avg_click_rate      numeric(6,5)  default 0,
  avg_rpr             numeric(8,5)  default 0,
  total_unsubscribes  integer     default 0,
  list_size           integer     default 0,

  -- Month-over-month
  prev_revenue        numeric(10,2) default 0,
  prev_open_rate      numeric(6,5)  default 0,
  prev_click_rate     numeric(6,5)  default 0,

  -- Recommendations summary
  critical_count      integer default 0,
  high_count          integer default 0,
  recommendations     jsonb   default '[]',

  -- Full rendered report (stored for dashboard embed)
  report_html         text,

  -- Delivery tracking
  slack_sent          boolean default false,
  slack_sent_at       timestamptz
);

-- Speed up listing by month
create index if not exists monthly_email_reports_month_idx
  on monthly_email_reports (report_month desc);
